enum ACTIONS {
    // Global
    APP_STATUS = 'APP_STATUS',
    // User
    USER_PERFORM_REGISTER = 'USER_PERFORM_REGISTER',
    USER_REQUEST_TOKEN = 'USER_REQUEST_TOKEN',
    USER_LOAD_DATA = 'USER_LOAD_DATA',
    USER_GET_REGISTER = 'USER_GET_REGISTER',
    USER_LOGOUT = 'USER_LOGOUT',
    USER_CHANGE_STATE = 'USER_CHANGE_STATE',
    USER_CHANGE_LOCATION = 'USER_CHANGE_LOCATION',
    // Notifications
    NOTIFICATION_CREATE = 'NOTIFICATION_CREATE',
}

export default ACTIONS;
